SCROLL_DOWN = 1
SCROLL_RIGHT = 2
SCROLL_LEFT = 3
SCROLL_UP = 4


def scroll_tick(*args): ...
def scroll_stop(*args): ...
def scroll_decelerate(*args): ...
def scroll_accelerate(*args): ...
def scroll_impart_impulse(*args): ...
